# Generated by Django 4.1.7 on 2023-04-03 03:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='文章相对数据库的唯一ID', primary_key=True, serialize=False)),
                ('remark', models.CharField(max_length=500)),
                ('due_release', models.DateTimeField()),
                ('due_modify', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.article')),
            ],
            options={
                'ordering': ['-due_modify'],
            },
        ),
    ]
