# Generated by Django 4.1.7 on 2023-04-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_articleinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='GithubURL',
            field=models.URLField(blank=True),
        ),
    ]
