# Generated by Django 4.1.7 on 2023-04-03 07:54

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_githuburl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AddField(
            model_name='article',
            name='due_modify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='due_release',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='remark',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='data_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='文章相对数据库的唯一ID', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ArticleInstance',
        ),
    ]
