# Generated by Django 4.1.7 on 2023-04-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_article_id_article_due_modify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='due_release',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
