# Generated by Django 4.1.7 on 2023-04-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_article_due_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='due_release',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
