# Generated by Django 4.1.7 on 2023-04-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_article_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='genre',
            field=models.ManyToManyField(help_text='选择本文章的类型', to='catalog.genre'),
        ),
    ]
