# Generated by Django 4.1.7 on 2023-04-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_article_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Check_Upload',
            field=models.BooleanField(default=False, help_text='是否上传云数据库'),
        ),
    ]
